use super::input_manager::KeyboardKey;

pub const NUMBER_0: KeyboardKey = 9;

pub const A: KeyboardKey = 10;
pub const B: KeyboardKey = 11;
pub const C: KeyboardKey = 12;
pub const D: KeyboardKey = 13;
pub const E: KeyboardKey = 14;
pub const F: KeyboardKey = 15;
pub const G: KeyboardKey = 16;
pub const H: KeyboardKey = 17;
pub const I: KeyboardKey = 18;
pub const J: KeyboardKey = 19;
pub const K: KeyboardKey = 20;
pub const L: KeyboardKey = 21;
pub const M: KeyboardKey = 22;
pub const N: KeyboardKey = 23;
pub const O: KeyboardKey = 24;
pub const P: KeyboardKey = 25;
pub const Q: KeyboardKey = 26;
pub const R: KeyboardKey = 27;
pub const S: KeyboardKey = 28;
pub const T: KeyboardKey = 29;
pub const U: KeyboardKey = 30;
pub const V: KeyboardKey = 31;
pub const W: KeyboardKey = 32;
pub const X: KeyboardKey = 33;
pub const Y: KeyboardKey = 34;
pub const Z: KeyboardKey = 35;
